// layout.tsx
import "./globals.css";

import Footer from "@/components/reusable/Footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Navbar from "@/components/navbar/navbar";
import NextAuthProvider from "@/components/NextAuthProvider";
import { authOptions } from "@/lib/AuthOptions";
import { cn } from "@/lib/utils";
import { getServerSession } from "next-auth/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <body className={cn(inter.className, "dark w-screen overflow-x-hidden")}>
        <NextAuthProvider session={session}>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="main-content mt-[100px]">{children}</main>
            <Footer />
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
